description: Princeton News Disinformation Study
repo-prefix: newsdisinformationstudy
active: true
private-repo: false
artifacts:
  - web-ext-artifacts/news-disinformation-study.xpi
addon-type: privileged
install-type: npm
